---
all:
  children:
    rhel_servers:
      hosts:
        rhel-lab-01:
          ansible_host: 192.0.2.10
        rhel-lab-02:
          ansible_host: 192.0.2.11
      vars:
        ansible_user: automation
        ansible_become: true